name: news_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_route: 7.8.0
  bloc: ^8.1.2
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.8.1
  meta: ^1.9.1
  url_launcher: ^6.1.14
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
