// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBywzN1Ynjo3-ombRosrH6XbpxwqXAcs8E',
    appId: '1:191027398037:web:82a2cb7190e6734752629c',
    messagingSenderId: '191027398037',
    projectId: 'news-sample-e418c',
    authDomain: 'news-sample-e418c.firebaseapp.com',
    storageBucket: 'news-sample-e418c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUUTFCBQzzJJIOXWqmIFPmRD5z_h_uQTM',
    appId: '1:191027398037:android:b6e1237fd85f501652629c',
    messagingSenderId: '191027398037',
    projectId: 'news-sample-e418c',
    storageBucket: 'news-sample-e418c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5F-HA5F7LNxQKPT4AXLWrmV5Pygurjy0',
    appId: '1:191027398037:ios:49126439e429f79852629c',
    messagingSenderId: '191027398037',
    projectId: 'news-sample-e418c',
    storageBucket: 'news-sample-e418c.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5F-HA5F7LNxQKPT4AXLWrmV5Pygurjy0',
    appId: '1:191027398037:ios:64e10e322d90db0452629c',
    messagingSenderId: '191027398037',
    projectId: 'news-sample-e418c',
    storageBucket: 'news-sample-e418c.appspot.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
